# Generated by Django 5.0.3 on 2024-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
        ),
    ]
