# Generated by Django 5.0.3 on 2024-03-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Teste', max_length=200, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='1234', max_length=20, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
    ]
