# Generated by Django 5.0.3 on 2024-03-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_nome_usuario_senha_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
