# Generated by Django 5.0.3 on 2024-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=100, null=True, verbose_name='Complemento'),
        ),
    ]
