# Generated by Django 5.0.3 on 2024-03-23 21:30

import animal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/image/default_cat.jpg', upload_to='image/')),
                ('is_default', models.BooleanField(default=False, validators=[animal.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='TemperamentAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('coat', models.CharField(max_length=100)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Pequeno porte'), ('medium', 'Médio porte'), ('large', 'Grande porte')], max_length=100, null=True)),
                ('specie', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato')], max_length=100)),
                ('adoption_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_house_trained', models.BooleanField()),
                ('is_special_needs', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.imageanimal')),
                ('temperament', models.ManyToManyField(blank=True, to='animal.temperamentanimal')),
            ],
        ),
    ]
