# Generated by Django 5.0.3 on 2024-03-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperamentanimal',
            name='name',
            field=models.CharField(choices=[('affectionate', 'Dengoso'), ('aggressive', 'Agressivo'), ('calm', 'Calmo'), ('energetic', 'Energético'), ('friendly', 'Amigável'), ('playful', 'Brincalhão'), ('shy', 'Arrisco'), ('sociable', 'Sociável'), ('territorial', 'Territorial')], max_length=100),
        ),
    ]
