# Generated by Django 5.0.3 on 2024-03-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_temperamentanimal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.DeleteModel(
            name='ImageAnimal',
        ),
    ]
