# Generated by Django 5.0.3 on 2024-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_alter_animal_age_alter_animal_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Pequeno porte'), ('medium', 'Médio porte'), ('large', 'Grande porte')], max_length=100, null=True),
        ),
    ]
