# Generated by Django 5.0.3 on 2024-04-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0008_imageanimal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="genre",
            new_name="gender",
        ),
    ]
