# Generated by Django 5.0.3 on 2024-04-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0009_rename_genre_animal_gender"),
        ("user", "0002_address_adopter"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_adopted",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.adopter",
            ),
        ),
    ]
