# Generated by Django 5.0.3 on 2024-04-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0010_animal_is_adopted"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="register_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.IntegerField(
                choices=[("puppy", "Filhote"), ("adult", "Adulto"), ("old", "Idoso")],
                default=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animal",
            name="coat",
            field=models.CharField(
                blank=True,
                choices=[("short", "Curto"), ("medium", "Médio"), ("long", "Longo")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(choices=[("M", "Macho"), ("F", "Fêmea")]),
        ),
        migrations.AlterField(
            model_name="animal",
            name="specie",
            field=models.CharField(choices=[("dog", "Cachorro"), ("cat", "Gato")]),
        ),
    ]
