# Generated by Django 5.0.3 on 2024-04-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0011_animal_register_date_alter_animal_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.CharField(
                choices=[("puppy", "Filhote"), ("adult", "Adulto"), ("old", "Idoso")]
            ),
        ),
    ]
