# Generated by Django 5.0.3 on 2024-04-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0012_alter_animal_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="temperament",
        ),
        migrations.DeleteModel(
            name="TemperamentAnimal",
        ),
        migrations.AddField(
            model_name="animal",
            name="temperament",
            field=models.CharField(blank=True, null=True),
        ),
    ]
