# Generated by Django 5.0.3 on 2024-04-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0013_remove_animal_temperament_delete_temperamentanimal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_castrated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_vaccinated",
            field=models.BooleanField(default=True),
        ),
    ]
