# Generated by Django 5.0.3 on 2024-04-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0015_alter_animal_is_castrated_alter_animal_is_vaccinated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="is_adopted",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
