# Generated by Django 5.0.3 on 2024-04-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0016_alter_animal_is_adopted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageanimal",
            name="image",
            field=models.ImageField(default="", upload_to="image/animals/"),
        ),
    ]
