# Generated by Django 5.0.3 on 2024-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="request_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("pending", "Pendente"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
