# Generated by Django 5.0.3 on 2024-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_address_adopter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="number",
            new_name="house_number",
        ),
        migrations.AlterField(
            model_name="adopter",
            name="phone",
            field=models.CharField(max_length=11),
        ),
    ]
