# Generated by Django 5.0.3 on 2024-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_number_address_house_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="", upload_to="image/"),
        ),
    ]
