# Generated by Django 5.0.3 on 2024-04-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_adopter_address_remove_adopter_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="image/avatar/"
            ),
        ),
    ]
