# Generated by Django 5.0.3 on 2024-03-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_endereco_alter_usuario_nome_alter_usuario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.endereco'),
            preserve_default=False,
        ),
    ]
