# Generated by Django 5.0.3 on 2024-04-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopter", "0001_initial"),
        ("animal", "0017_alter_imageanimal_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("request_status", models.CharField(blank=True, null=True)),
                (
                    "adopter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adopter.adopter",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_registers",
                        to="animal.animal",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_registers",
                        to="animal.animal",
                    ),
                ),
            ],
        ),
    ]
